-- Criação dos registros na tabela pagamentos
INSERT INTO pagamento (forma_de_pagamento, status_do_pagamento)
VALUES
    ('Cartão de Crédito', 'Aprovado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Aprovado'),
    ('Transferência Bancária', 'Cancelado'),
    ('Boleto Bancário', 'Pendente'),
    ('Cartão de Crédito', 'Recusado'),
    ('Pix', 'Pendente'),
    ('Transferência Bancária', 'Aprovado'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Recusado'),
    ('Transferência Bancária', 'Pendente'),
    ('Cartão de Crédito', 'Recusado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Aprovado'),
    ('Transferência Bancária', 'Cancelado'),
    ('Cartão de Crédito', 'Pendente'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Aprovado'),
    ('Transferência Bancária', 'Recusado'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Pix', 'Pendente'),
    ('Boleto Bancário', 'Recusado'),
    ('Cartão de Crédito', 'Cancelado'),
    ('Pix', 'Pendente'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Transferência Bancária', 'Recusado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Aprovado'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Transferência Bancária', 'Cancelado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Pendente'),
    ('Cartão de Crédito', 'Recusado'),
    ('Transferência Bancária', 'Aprovado'),
    ('Pix', 'Pendente'),
    ('Boleto Bancário', 'Recusado'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Transferência Bancária', 'Cancelado'),
    ('Pix', 'Aprovado'),
    ('Boleto Bancário', 'Pendente'),
    ('Cartão de Crédito', 'Pendente'),
    ('Pix', 'Recusado'),
    ('Transferência Bancária', 'Recusado'),
    ('Cartão de Crédito', 'Cancelado'),
    ('Boleto Bancário', 'Pendente'),
    ('Pix', 'Aprovado'),
    ('Transferência Bancária', 'Pendente'),
    ('Cartão de Crédito', 'Aprovado'),
    ('Boleto Bancário', 'Recusado');
