-- criaçaõ dos registros da tabela estoque
INSERT INTO estoque (quantidade, localizacao, estoque_fornecedor)
VALUES
    (150, 'Armazém Central - São Paulo', 1),
    (75, 'Depósito Zona Sul - Rio de Janeiro', 2),
    (200, 'Centro de Distribuição - Belo Horizonte', 3),
    (60, 'Armazém Paraná - Curitiba', 4),
    (90, 'Galpão Porto Alegre', 5),
    (40, 'Depósito Brasília', 6),
    (120, 'Centro de Distribuição Salvador', 7),
    (110, 'Depósito Fortaleza', 8),
    (50, 'Armazém - Belo Horizonte', 9),
    (100, 'Centro de Distribuição - Vitória', 10),
    (130, 'Depósito Campinas', 11),
    (85, 'Armazém Zona Norte - Campinas', 12),
    (95, 'Armazém Cuiabá', 13),
    (70, 'Galpão Belo Horizonte', 14),
    (45, 'Depósito Zona Oeste - Rio de Janeiro', 15),
    (80, 'Centro de Distribuição Salvador', 16),
    (160, 'Armazém - São Paulo', 17),
    (135, 'Depósito Central Florianópolis', 18),
    (90, 'Galpão Goiânia', 19),
    (55, 'Armazém Joinville', 20),
    (75, 'Depósito Campinas', 21),
    (100, 'Centro de Distribuição - João Pessoa', 22),
    (50, 'Armazém Ribeirão Preto', 23),
    (115, 'Armazém Blumenau', 24),
    (80, 'Depósito Porto Velho', 25),
    (60, 'Centro de Distribuição - Rio de Janeiro', 26),
    (150, 'Depósito Belém', 27),
    (45, 'Depósito Boa Vista', 28),
    (110, 'Galpão Porto Alegre', 29),
    (95, 'Armazém Cascavel', 30),
    (130, 'Depósito Zona Oeste - BH', 31),
    (65, 'Centro de Distribuição - Campinas', 32),
    (105, 'Galpão Cuiabá', 33),
    (55, 'Depósito Salvador', 34),
    (70, 'Armazém Fortaleza', 35),
    (50, 'Depósito Boa Vista', 36),
    (140, 'Armazém Manaus', 37),
    (95, 'Centro de Distribuição - Campo Grande', 38),
    (80, 'Depósito Joinville', 39),
    (110, 'Galpão - Porto Alegre', 40),
    (75, 'Centro de Distribuição Santos', 41),
    (60, 'Armazém Vitória', 42),
    (120, 'Depósito Belo Horizonte', 43),
    (100, 'Galpão Florianópolis', 44),
    (95, 'Depósito São Paulo', 45),
    (130, 'Centro de Distribuição - Rio de Janeiro', 46),
    (85, 'Armazém João Pessoa', 47),
    (55, 'Galpão Boa Vista', 48),
    (90, 'Depósito Blumenau', 49),
    (75, 'Armazém Porto Alegre', 50);
